module Seeds

    def self.seed_courses
        make Course do
            within :cs do
make(%q(Introduction to Computing at Stanford), '1C', 1, 1).includes ["Aut"]
make(%q(Practical Unix), '1U', 1, 1).includes ["Aut", "Win", "Spr"]
make(%q(Multimedia Production), '2C', 1, 2).includes ["Aut", "Win"]
make(%q(Problem-Solving for the CS Technical Interview), '9', 1, 1).includes ["Win"]
make(%q(Great Ideas in Computer Science), '10SC', 2, 2).includes ["not given this year"]
make(%q(Can Machines Know? Can Machines Feel?), '21N', 3, 3).includes ["Aut"]
make(%q(History and Philosophy of Artificial Intelligence (SYMSYS 22)), '22', 2, 2).includes ["Aut"]
make(%q(Computers and Photography: From Capture to Sharing), '45N', 3, 4).includes ["Aut"]
make(%q(Great Ideas in Computer Science), '54N', 3, 3).includes ["Aut"]
make(%q(Great Discoveries and Inventions in Computing), '56N', 3, 3).includes ["Win"]
make(%q(The Business of the Internet), '73N', 3, 3).includes ["Spr"]
make(%q(Digital Dilemmas), '74N', 3, 3).includes ["Aut"]
make(%q(Cell Phones, Sensors, and You), '75N', 3, 3).includes ["not given this year"]
make(%q(Interaction Design Basics), '77', 2, 2).includes ["Win"]
make(%q(Understanding Women's Experience in High-Tech Companies), '78', 3, 3).includes ["Win"]
make(%q(Code the Change: Learn Web Development Through Nonprofit Projects), '90SI', 2, 2).includes ["Aut", "Spr"]
make(%q(Introduction to Functional Programming in Haskell), '93SI', 1, 1).includes ["Win"]
make(%q(Callback Me Maybe: Contemporary JavaScript), '99SI', 2, 2).includes ["Aut", "Spr"]
make(%q(Introduction to Computing Principles), '101', 3, 5).includes ["Spr"]
make(%q(Mathematical Foundations of Computing), '103', 3, 5).includes ["Aut", "Win", "Spr"]
make(%q(Introduction to Computers), '105', 3, 5).includes ["Aut", "Win"]
make(%q(Programming Methodology (ENGR 70A)), '106A', 3, 5).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Programming Abstractions (ENGR 70B)), '106B', 3, 5).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Standard C++ Programming Laboratory), '106L', 1, 1).includes ["Aut", "Spr"]
make(%q(Programming Abstractions (Accelerated) (ENGR 70X)), '106X', 3, 5).includes ["Aut", "Win"]
make(%q(Computer Organization and Systems), '107', 3, 5).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Object-Oriented Systems Design), '108', 3, 4).includes ["Aut", "Win"]
make(%q(Introduction to Probability for Computer Scientists), '109', 3, 5).includes ["Win", "Spr", "Sum"]
make(%q(Statistical Computing with R Laboratory), '109L', 1, 1).includes ["Win", "Spr"]
make(%q(Principles of Computer Systems), '110', 3, 5).includes ["Aut", "Win", "Spr"]
make(%q(From Languages to Information (LINGUIST 180, LINGUIST 280)), '124', 3, 4).includes ["Win"]
make(%q(Computer Vision: Foundations and Applications), '131', 3, 4).includes ["Aut"]
make(%q(Operating Systems and Systems Programming), '140', 3, 4).includes ["Win", "Spr"]
make(%q(Web Applications), '142', 3, 3).includes ["Win", "Spr"]
make(%q(Compilers), '143', 3, 4).includes ["Spr", "Sum"]
make(%q(Introduction to Computer Networking), '144', 3, 4).includes ["Aut"]
make(%q(Introduction to Databases), '145', 3, 4).includes ["Aut", "Sum"]
make(%q(Introduction to Human-Computer Interaction Design), '147', 3, 4).includes ["Win"]
make(%q(Introduction to Computer Graphics and Imaging), '148', 3, 4).includes ["Aut", "Sum"]
make(%q(Parallel Computing), '149', 3, 4).includes ["Win"]
make(%q(Introduction to Automata and Complexity Theory), '154', 3, 4).includes ["Win"]
make(%q(Computer and Network Security), '155', 3, 3).includes ["Spr"]
make(%q(Logic and Automated Reasoning), '157', 3, 3).includes ["Aut"]
make(%q(Design and Analysis of Algorithms), '161', 3, 5).includes ["Aut", "Spr", "Sum"]
make(%q(Implementation of Algorithms), '161L', 1, 1).includes ["Spr"]
make(%q(Computing with Physical Objects: Algorithms for Shape and Motion), '164', 3, 3).includes ["not given this year"]
make(%q(Data Structures), '166', 3, 4).includes ["Spr"]
make(%q(Readings in Algorithms), '167', 3, 3).includes ["Spr"]
make(%q(Stanford Laptop Orchestra: Composition, Coding, and Performance (MUSIC 128)), '170', 1, 5).includes ["Spr"]
make(%q(A Computational Tour of the Human Genome), '173', 3, 3).includes ["not given this year"]
make(%q(Digital Photography), '178', 3, 5).includes ["Spr"]
make(%q(Computers, Ethics, and Public Policy), '181', 4, 4).includes ["Aut", "Win", "Spr"]
make(%q(Computers, Ethics, and Public Policy (WIM)), '181W', 4, 4).includes ["Aut", "Win", "Spr"]
make(%q(Senior Project), '191', 1, 6).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Writing Intensive Senior Project (WIM)), '191W', 3, 6).includes ["Aut", "Win", "Spr"]
make(%q(Programming Service Project), '192', 1, 4).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Client-Side Internet Technologies), '193C', 3, 3).includes ["Sum"]
make(%q(iPhone and iPad Application Programming), '193P', 3, 3).includes ["Aut", "Spr"]
make(%q(Software Project), '194', 3, 3).includes ["Win", "Spr"]
make(%q(Software Project (WIM)), '194W', 3, 3).includes ["Win", "Spr"]
make(%q(Computer Consulting), '196', 2, 2).includes ["Win", "Spr"]
make(%q(Teaching Computer Science), '198', 3, 4).includes ["Aut", "Win", "Spr"]
make(%q(Independent Work), '199', 1, 6).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Independent Work), '199P', 1, 6).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Care and Feeding of Large-Scale Web Services), '200', 1, 1).includes ["Spr"]
make(%q(Law for Computer Science Professionals), '202', 1, 1).includes ["Spr"]
make(%q(Legal Informatics), '204', 3, 3).includes ["Spr"]
make(%q(Mathematical Methods for Robotics, Vision, and Graphics), '205A', 3, 3).includes ["Aut"]
make(%q(Mathematical Methods for Fluids, Solids, and Interfaces), '205B', 3, 3).includes ["not given this year"]
make(%q(The Economics of Software), '207', 2, 2).includes ["Aut"]
make(%q(Software Project Experience with Corporate Partners), '210A', 3, 4).includes ["Win"]
make(%q(Software Project Experience with Corporate Partners), '210B', 3, 4).includes ["Spr"]
make(%q(Artificial Intelligence: Principles and Techniques), '221', 3, 4).includes ["Aut"]
make(%q(Rational Agency and Intelligent Interaction (PHIL 358)), '222', 3, 3).includes ["not given this year"]
make(%q(Introduction to Robotics (ME 320)), '223A', 3, 3).includes ["Win"]
make(%q(Multi-Agent Systems), '224M', 3, 3).includes ["Spr"]
make(%q(Natural Language Processing (LINGUIST 284)), '224N', 3, 4).includes ["Aut"]
make(%q(Spoken Language Processing (LINGUIST 285)), '224S', 2, 4).includes ["Spr"]
make(%q(Natural Language Understanding (LINGUIST 188, LINGUIST 288)), '224U', 3, 4).includes ["Spr"]
make(%q(Social and Information Network Analysis), '224W', 3, 4).includes ["Aut"]
make(%q(Experimental Robotics), '225A', 3, 3).includes ["not given this year"]
make(%q(Robot Programming Laboratory), '225B', 3, 4).includes ["not given this year"]
make(%q(Statistical Techniques in Robotics), '226', 3, 3).includes ["not given this year"]
make(%q(General Game Playing), '227B', 3, 3).includes ["Spr"]
make(%q(Probabilistic Graphical Models: Principles and Techniques), '228', 3, 4).includes ["Win"]
make(%q(Machine Learning), '229', 3, 4).includes ["Aut"]
make(%q(Statistical Learning Theory (STATS 231)), '229T', 3, 3).includes ["Win"]
make(%q(Computer Vision: From 3D Reconstruction to Recognition), '231A', 3, 4).includes ["Win"]
make(%q(The Cutting Edge of Computer Vision), '231B', 3, 3).includes ["not given this year"]
make(%q(Mobile Computer Vision), '231M', 3, 4).includes ["Spr"]
make(%q(Digital Image Processing (EE 368)), '232', 3, 3).includes ["Aut", "Win", "Spr"]
make(%q(Advanced Topics in Operating Systems), '240', 3, 3).includes ["Spr"]
make(%q(Embedded Wireless Systems), '240E', 3, 3).includes ["Spr"]
make(%q(Functional Systems in Haskell), '240H', 3, 4).includes ["Spr"]
make(%q(Programming Languages), '242', 3, 3).includes ["Aut"]
make(%q(Program Analysis and Optimizations), '243', 3, 4).includes ["Win"]
make(%q(Advanced Topics in Networking), '244', 3, 4).includes ["Spr"]
make(%q(Distributed Systems), '244B', 3, 3).includes ["Spr"]
make(%q(Readings and Projects in Distributed Systems), '244C', 3, 6).includes ["offered occasionally"]
make(%q(Networked Wireless Systems), '244E', 3, 3).includes ["not given this year"]
make(%q(Database Systems Principles), '245', 3, 3).includes ["Win"]
make(%q(Mining Massive Data Sets), '246', 3, 4).includes ["Win"]
make(%q(Mining Massive Data Sets Hadoop Lab), '246H', 1, 1).includes ["Win"]
make(%q(Human-Computer Interaction Design Studio), '247', 3, 4).includes ["Spr"]
make(%q(Human Computer Interaction Technology Laboratory), '247L', 1, 1).includes ["Spr"]
make(%q(Interactive Computer Graphics), '248', 3, 4).includes ["Win"]
make(%q(Object-Oriented Programming from a Modeling and Simulation Perspective), '249A', 3, 3).includes ["Aut"]
make(%q(Large-scale Software Development), '249B', 3, 3).includes ["not given this year"]
make(%q(Computational Complexity), '254', 3, 3).includes ["Win"]
make(%q(Introduction to Cryptography), '255', 3, 3).includes ["Win"]
make(%q(Optimization and Algorithmic Paradigms), '261', 3, 3).includes ["Win"]
make(%q(Computational Genomics (BIOMEDIN 262)), '262', 3, 3).includes ["Win"]
make(%q(Algorithms for Modern Data Models (MS&E 317)), '263', 3, 3).includes ["Spr"]
make(%q(Randomized Algorithms and Probabilistic Analysis (CME 309)), '265', 3, 3).includes ["Aut"]
make(%q(Parameterized Algorithms and Complexity), '266', 3, 3).includes ["not given this year"]
make(%q(Graph Algorithms), '267', 3, 3).includes ["Win"]
make(%q(Modeling Biomedical Systems: Ontology, Terminology, Problem Solving (BIOMEDIN 210)), '270', 3, 3).includes ["Win"]
make(%q(Introduction to Biomedical Informatics Research Methodology (BIOE 212, BIOMEDIN 212, GENE 212)), '272', 3, 3).includes ["Spr"]
make(%q(A Computational Tour of the Human Genome (BIOMEDIN 273A, DBIO 273A)), '273A', 3, 3).includes ["Aut"]
make(%q(Representations and Algorithms for Computational Molecular Biology (BIOE 214, BIOMEDIN 214, GENE 214)), '274', 3, 4).includes ["Aut"]
make(%q(Translational Bioinformatics (BIOMEDIN 217)), '275', 4, 4).includes ["Win"]
make(%q(Symbolic Musical Information (MUSIC 253)), '275A', 2, 4).includes ["Win"]
make(%q(Music Query, Analysis, and Style Simulation (MUSIC 254)), '275B', 2, 4).includes ["Spr"]
make(%q(Information Retrieval and Web Search (LINGUIST 286)), '276', 3, 3).includes ["Spr"]
make(%q(Experimental Haptics), '277', 3, 3).includes ["Spr"]
make(%q(Research Project in Computer Science), '294', 3, 3).includes ["offered occasionally"]
make(%q(Research Project in Artificial Intelligence), '294A', 3, 3).includes ["not given this year"]
make(%q(Research Project in Human-Computer Interaction), '294H', 3, 3).includes ["not given this year"]
make(%q(Software Engineering), '295', 2, 3).includes ["not given this year"]
make(%q(Seminar on Teaching Introductory Computer Science), '298', 1, 3).includes ["not given this year"]
make(%q(Departmental Lecture Series), '300', 1, 1).includes ["Aut"]
make(%q(Industrial Lectureships in Computer Science), '309', 1, 1).includes ["offered occasionally"]
make(%q(Cloud Computing), '309A', 1, 1).includes ["Aut"]
make(%q(Parallel Computer Architecture and Programming), '315A', 3, 3).includes ["not given this year"]
make(%q(Parallel Computing Research Project), '315B', 3, 3).includes ["not given this year"]
make(%q(Advanced Multi-Core Systems (EE 382E)), '316', 3, 3).includes ["Aut"]
make(%q(Topics in Digital Systems), '319', 3, 3).includes ["offered occasionally"]
make(%q(Topics in Computer Vision), '328', 3, 3).includes ["offered occasionally"]
make(%q(Topics in Artificial Intelligence), '329', 3, 3).includes ["offered occasionally"]
make(%q(Advanced Reading in Computer Vision), '331A', 3, 3).includes ["Win"]
make(%q(3D Representation and Recognition), '331B', 3, 3).includes ["Aut"]
make(%q(Convex Optimization I (CME 364A, EE 364A)), '334A', 3, 3).includes ["Win", "Sum"]
make(%q(Topics in Computer Systems), '340', 3, 4).includes ["offered occasionally"]
make(%q(Project in Mining Massive Data Sets), '341', 3, 3).includes ["Spr"]
make(%q(Advanced Topics in Compilers), '343', 3, 3).includes ["Spr"]
make(%q(Topics in Computer Networks), '344', 3, 3).includes ["not given this year"]
make(%q(Advanced Wireless Networks), '344E', 3, 3).includes ["not given this year"]
make(%q(Topics in Database Systems), '345D', 3, 3).includes ["Win"]
make(%q(Database System Implementation), '346', 3, 5).includes ["Spr"]
make(%q(Parallel and Distributed Data Management), '347', 3, 3).includes ["Spr"]
make(%q(Computer Graphics: Geometric Modeling), '348A', 3, 4).includes ["Win"]
make(%q(Computer Graphics: Image Synthesis Techniques), '348B', 3, 4).includes ["Spr"]
make(%q(Topics in Programming Systems), '349', 3, 3).includes ["offered occasionally"]
make(%q(Topics in Programming Systems: Readings in Distributed Systems), '349C', 1, 3).includes ["not given this year"]
make(%q(Topics in Circuit Complexity), '354', 3, 3).includes ["Spr"]
make(%q(Advanced Topics in Cryptography), '355', 3, 3).includes ["Spr"]
make(%q(Advanced Topics in Formal Methods), '357', 3, 3).includes ["Aut"]
make(%q(Topics in Programming Language Theory), '358', 3, 3).includes ["offered occasionally"]
make(%q(Topics in the Theory of Computation), '359', 3, 3).includes ["offered occasionally"]
make(%q(Advanced Algorithms), '361A', 3, 3).includes ["not given this year"]
make(%q(Advanced Algorithms), '361B', 3, 3).includes ["Spr"]
make(%q(Algorithmic Frontiers: Effective Algorithms for Large Data), '362', 3, 3).includes ["Spr"]
make(%q(Algorithmic Game Theory), '364A', 3, 3).includes ["Aut"]
make(%q(Topics in Algorithmic Game Theory), '364B', 3, 3).includes ["Win"]
make(%q(Algebraic Graph Algorithms), '367', 3, 3).includes ["Spr"]
make(%q(Topics in Analysis of Algorithms), '369', 3, 3).includes ["offered occasionally"]
make(%q(Beyond Worst-Case Analysis), '369N', 3, 3).includes ["not given this year"]
make(%q(Computational Biology in Four Dimensions (CME 371)), '371', 3, 3).includes ["Spr"]
make(%q(Algorithms in Biology (BIOMEDIN 374)), '374', 2, 3).includes ["Spr"]
make(%q(Research Topics in Human-Computer Interaction), '376', 3, 4).includes ["Spr"]
make(%q(Topics in Human-Computer Interaction), '377', 2, 3).includes ["offered occasionally"]
make(%q(Topics in Learning and Technology: d.compress - Designing Calm (EDUC 328A)), '377D', 2, 3).includes ["not given this year"]
make(%q(Learning in a Networked World: Learning Analytics in Technology-Enhanced Education (EDUC 298)), '377L', 3, 3).includes ["not given this year"]
make(%q(HCI Issues in Wearable Computing), '377W', 3, 3).includes ["Spr"]
make(%q(Interdisciplinary Topics), '379', 3, 3).includes ["offered occasionally"]
make(%q(Designing Liberation Technology (POLISCI 337T)), '379L', 3, 4).includes ["Spr"]
make(%q(Curricular Practical Training), '390A', 1, 1).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Curricular Practical Training), '390B', 1, 1).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Curricular Practical Training), '390C', 1, 1).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Computer Laboratory), '393', 1, 9).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Independent Database Project), '395', 1, 6).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Independent Project), '399', 1, 9).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Independent Project), '399P', 1, 9).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Beyond Bits and Atoms: Designing Technological Tools (EDUC 236X)), '402', 3, 5).includes ["not given this year"]
make(%q(Beyond Bits and Atoms - Lab (EDUC 211X)), '402L', 1, 3).includes ["not given this year"]
make(%q(Learning Analytics and Computational Modeling in Social Science (EDUC 390X)), '424M', 3, 4).includes ["not given this year"]
make(%q(High-Level Vision: Object Representation (PSYCH 250)), '431', 3, 3).includes ["Spr"]
make(%q(High Productivity and Performance with Domain-specific Languages in Scala), '442', 3, 3).includes ["not given this year"]
make(%q(Software Design Experiences), '447', 3, 4).includes ["not given this year"]
make(%q(Topics in Computer Graphics), '448', 3, 4).includes ["offered occasionally"]
make(%q(Data Visualization), '448B', 3, 3).includes ["not given this year"]
make(%q(Topics in Geometric Algorithms:Data-Driven Shape Analysis), '468', 3, 3).includes ["Win", "Spr"]
make(%q(Music, Computing, and Design I: Software Paradigms for Computer Music (MUSIC 256A)), '476A', 1, 4).includes ["Aut"]
make(%q(Music, Computing, Design II: Mobile Music (MUSIC 256B)), '476B', 1, 4).includes ["Win"]
make(%q(Advanced Reading and Research), '499', 1, 15).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Advanced Reading and Research), '499P', 1, 15).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Database and Information Management Seminar), '545', 1, 1).includes ["Win"]
make(%q(Seminar on Liberation Technologies (POLISCI 337S)), '546', 1, 1).includes ["Aut", "Win"]
make(%q(Human-Computer Interaction Seminar), '547', 1, 1).includes ["Aut", "Win", "Spr"]
make(%q(Internet and Distributed Systems Seminar), '548', 1, 1).includes ["not given this year"]
make(%q(Human-Computer Interaction in the Real World), '549', 1, 1).includes ["Spr"]
make(%q(TGR Project), '801', 0, 0).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(TGR Dissertation), '802', 0, 0).includes ["Aut", "Win", "Spr", "Sum"]
            end

            within :math do
make(%q(Mathematics and Statistics in the Real World (STATS 90)), '16', 3, 3).includes ["not given this year"]
make(%q(Calculus), '19', 3, 3).includes ["Aut", "Win", "Sum"]
make(%q(Calculus), '20', 3, 3).includes ["Win", "Spr"]
make(%q(Calculus), '21', 4, 4).includes ["Spr"]
make(%q(Calculus (accelerated)), '41', 5, 5).includes ["Aut"]
make(%q(Calculus ACE), '41A', 6, 6).includes ["Aut"]
make(%q(Calculus (Accelerated)), '42', 5, 5).includes ["Aut", "Win"]
make(%q(Calculus ACE), '42A', 6, 6).includes ["Aut", "Win"]
make(%q(Linear Algebra and Differential Calculus of Several Variables), '51', 5, 5).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Linear Algebra and Differential Calculus of Several Variables, ACE), '51A', 6, 6).includes ["Aut", "Win", "Spr"]
make(%q(Honors Multivariable Mathematics), '51H', 5, 5).includes ["Aut"]
make(%q(Introduction to MATLAB for Multivariable Mathematics), '51M', 1, 1).includes ["Aut"]
make(%q(Integral Calculus of Several Variables), '52', 5, 5).includes ["Aut", "Win", "Spr"]
make(%q(Honors Multivariable Mathematics), '52H', 5, 5).includes ["Win"]
make(%q(Ordinary Differential Equations with Linear Algebra), '53', 5, 5).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Honors Multivariable Mathematics), '53H', 5, 5).includes ["Spr"]
make(%q(The Game of Go: Strategy, Theory, and History), '70SI', 1, 1).includes ["not given this year"]
make(%q(Speedcubing: HIstory, Theory, and Practice), '78SI', 1, 1).includes ["not given this year"]
make(%q(Capillary Surfaces: Explored and Unexplored Territory), '80Q', 3, 3).includes ["Spr"]
make(%q(Mathematics of Knots, Braids, Links, and Tangles), '87Q', 3, 3).includes ["Win"]
make(%q(The Mathematics of the Rubik's Cube), '88Q', 3, 3).includes ["not given this year"]
make(%q(Mathematics for Elementary School Teachers), '100', 4, 4).includes ["not given this year"]
make(%q(Applied Matrix Theory), '104', 3, 3).includes ["Win", "Spr", "Sum"]
make(%q(Functions of a Complex Variable), '106', 3, 3).includes ["Spr"]
make(%q(Introduction to Combinatorics and Its Applications), '108', 3, 3).includes ["Spr"]
make(%q(Applied Group Theory), '109', 3, 3).includes ["Win"]
make(%q(Applied Number Theory and Field Theory), '110', 3, 3).includes ["Spr"]
make(%q(Computational Commutative Algebra), '111', 3, 3).includes ["not given this year"]
make(%q(Linear Algebra and Matrix Theory), '113', 3, 3).includes ["Aut", "Win", "Spr"]
make(%q(Functions of a Real Variable), '115', 3, 3).includes ["Aut", "Spr"]
make(%q(Complex Analysis), '116', 3, 3).includes ["Win"]
make(%q(Mathematics of Computation), '118', 3, 3).includes ["Aut"]
make(%q(Groups and Rings), '120', 3, 3).includes ["Aut", "Spr"]
make(%q(Galois Theory), '121', 3, 3).includes ["Win"]
make(%q(Modules and Group Representations), '122', 3, 3).includes ["Spr"]
make(%q(Partial Differential Equations I), '131P', 3, 3).includes ["Aut", "Win"]
make(%q(Partial Differential Equations II), '132', 3, 3).includes ["not given this year"]
make(%q(Stochastic Processes (STATS 219)), '136', 3, 3).includes ["Aut"]
make(%q(Mathematical Methods of Classical Mechanics), '137', 3, 3).includes ["not given this year"]
make(%q(Celestial Mechanics), '138', 3, 3).includes ["not given this year"]
make(%q(Differential Geometry), '143', 3, 3).includes ["not given this year"]
make(%q(Riemannian Geometry), '144', 3, 3).includes ["Win"]
make(%q(Algebraic Geometry), '145', 3, 3).includes ["not given this year"]
make(%q(Analysis on Manifolds), '146', 3, 3).includes ["not given this year"]
make(%q(Differential Topology), '147', 3, 3).includes ["Spr"]
make(%q(Algebraic Topology), '148', 3, 3).includes ["not given this year"]
make(%q(Applied Algebraic Topology), '149', 3, 3).includes ["Win"]
make(%q(Introduction to Probability Theory), '151', 3, 3).includes ["Win"]
make(%q(Elementary Theory of Numbers), '152', 3, 3).includes ["Win"]
make(%q(Algebraic Number Theory), '154', 3, 3).includes ["alternate years", "given next year"]
make(%q(Analytic Number Theory), '155', 3, 3).includes ["Spr"]
make(%q(Discrete Probabilistic Methods), '159', 3, 3).includes ["Win"]
make(%q(Set Theory), '161', 3, 3).includes ["Aut"]
make(%q(Philosophy of Mathematics (PHIL 162, PHIL 262)), '162', 4, 4).includes ["not given this year"]
make(%q(The Greek Invention of Mathematics), '163', 3, 5).includes ["not given this year"]
make(%q(Fundamental Concepts of Analysis), '171', 3, 3).includes ["Aut", "Spr"]
make(%q(Lebesgue Integration and Fourier Analysis), '172', 3, 3).includes ["Win"]
make(%q(Theory of Partial Differential Equations), '173', 3, 3).includes ["Spr"]
make(%q(Calculus of Variations), '174', 3, 3).includes ["not given this year"]
make(%q(Elementary Functional Analysis), '175', 3, 3).includes ["Spr"]
make(%q(Introduction to Financial Mathematics), '180', 3, 3).includes ["not given this year"]
make(%q(Polya Problem Solving Seminar), '193', 1, 1).includes ["Aut"]
make(%q(Undergraduate Colloquium), '196', 1, 1).includes ["Aut", "Win", "Spr"]
make(%q(Senior Honors Thesis), '197', 1, 6).includes ["Aut", "Win", "Spr"]
make(%q(Practical Training), '198', 1, 1).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Independent Work), '199', 1, 3).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Real Analysis), '205A', 3, 3).includes ["Aut"]
make(%q(Real Analysis), '205B', 3, 3).includes ["Win"]
make(%q(Modern Algebra I), '210A', 3, 3).includes ["Aut"]
make(%q(Modern Algebra II), '210B', 3, 3).includes ["Win"]
make(%q(Lie Theory), '210C', 3, 3).includes ["Spr"]
make(%q(Complex Analysis, Geometry, and Topology), '215A', 3, 3).includes ["Aut"]
make(%q(Complex Analysis, Geometry, and Topology), '215B', 3, 3).includes ["Win"]
make(%q(Complex Analysis, Geometry, and Topology), '215C', 3, 3).includes ["Spr"]
make(%q(Introduction to Algebraic Geometry), '216A', 3, 3).includes ["Aut"]
make(%q(Introduction to Algebraic Geometry), '216B', 3, 3).includes ["Win"]
make(%q(Introduction to Algebraic Geometry), '216C', 3, 3).includes ["Spr"]
make(%q(Differential Geometry), '217A', 3, 3).includes ["Spr"]
make(%q(Partial Differential Equations of Applied Mathematics (CME 303)), '220', 3, 3).includes ["Aut"]
make(%q(Mathematical Methods of Imaging (CME 321A)), '221A', 3, 3).includes ["Win"]
make(%q(Mathematical Methods of Imaging (CME 321B)), '221B', 3, 3).includes ["Spr"]
make(%q(Computational Methods for Fronts, Interfaces, and Waves), '222', 3, 3).includes ["not given this year"]
make(%q(Topics in Mathematical Biology), '224', 3, 3).includes ["not given this year"]
make(%q(Numerical Solution of Partial Differential Equations (CME 306)), '226', 3, 3).includes ["Spr"]
make(%q(Partial Differential Equations and Diffusion Processes), '227', 3, 3).includes ["not given this year"]
make(%q(Stochastic Methods in Engineering (CME 308)), '228', 3, 3).includes ["Spr"]
make(%q(Theory of Probability (STATS 310A)), '230A', 2, 4).includes ["Aut"]
make(%q(Theory of Probability (STATS 310B)), '230B', 2, 3).includes ["Win"]
make(%q(Theory of Probability (STATS 310C)), '230C', 2, 4).includes ["Spr"]
make(%q(An Introduction to Random Matrix Theory (STATS 351A)), '231A', 3, 3).includes ["not given this year"]
make(%q(Free Probability), '231C', 3, 3).includes ["not given this year"]
make(%q(Topics in Probability: Percolation Theory), '232', 3, 3).includes ["not given this year"]
make(%q(Probabilistic Methods in Analysis), '233', 3, 3).includes ["not given this year"]
make(%q(Large Deviations Theory (STATS 374)), '234', 3, 3).includes ["not given this year"]
make(%q(Introduction to Stochastic Differential Equations), '236', 3, 3).includes ["Win"]
make(%q(Mathematical Finance (STATS 250)), '238', 3, 3).includes ["Win"]
make(%q(Computation and Simulation in Finance), '239', 3, 3).includes ["not given this year"]
make(%q(Functions of Several Complex Variables), '243', 3, 3).includes ["not given this year"]
make(%q(Riemann Surfaces), '244', 3, 3).includes ["not given this year"]
make(%q(Topics in Algebraic Geometry: Moduli Theory), '245A', 3, 3).includes ["Win"]
make(%q(Topics in Algebraic Geometry: Intersection Theory), '245B', 3, 3).includes ["not given this year"]
make(%q(Topics in Algebraic Geometry: Alterations), '245C', 3, 3).includes ["not given this year"]
make(%q(Topics in Group Theory), '247', 3, 3).includes ["not given this year"]
make(%q(Ergodic Theory and Szemeredi's Theorem), '248', 3, 3).includes ["not given this year"]
make(%q(Algebraic Number Theory), '248A', 3, 3).includes ["not given this year"]
make(%q(Topics in number theory), '249A', 3, 3).includes ["Aut"]
make(%q(Topics in Number Theory), '249B', 3, 3).includes ["Win"]
make(%q(Topics in Number Theory), '249C', 3, 3).includes ["Spr"]
make(%q(Algebraic Groups), '252', 3, 3).includes ["not given this year"]
make(%q(Geometric Methods in the Theory of Ordinary Differential Equations), '254', 3, 3).includes ["not given this year"]
make(%q(Partial Differential Equations), '256A', 3, 3).includes ["Spr"]
make(%q(Partial Differential Equations), '256B', 3, 3).includes ["Win"]
make(%q(Symplectic Geometry and Topology), '257A', 3, 3).includes ["not given this year"]
make(%q(Symplectic Geometry and Topology), '257B', 3, 3).includes ["not given this year"]
make(%q(Symplectic Geometry and Topology), '257C', 3, 3).includes ["Win"]
make(%q(Topics in Geometric Analysis), '258', 3, 3).includes ["Spr"]
make(%q(mirror symmetry), '259', 3, 3).includes ["not given this year"]
make(%q(Functional Analysis), '261A', 3, 3).includes ["not given this year"]
make(%q(Applied Fourier Analysis and Elements of Modern Signal Processing (CME 372)), '262', 3, 3).includes ["Win"]
make(%q(Infinite-dimensional Lie Algebras), '263A', 3, 3).includes ["Win"]
make(%q(Quantum Groups and the Yang-Baxter Equation), '263B', 3, 3).includes ["Spr"]
make(%q(Infinite Dimensional Lie Algebra), '264', 3, 3).includes ["not given this year"]
make(%q(Computational Signal Processing and Wavelets), '266', 3, 3).includes ["not given this year"]
make(%q(Topics in symplectic geometry), '269', 3, 3).includes ["Spr"]
make(%q(Geometry and Topology of Complex Manifolds), '270', 3, 3).includes ["not given this year"]
make(%q(The H-Principle), '271', 3, 3).includes ["not given this year"]
make(%q(Topics in Partial Differential Equations), '272', 3, 3).includes ["not given this year"]
make(%q(Quantum Mechanics I), '273A', 3, 3).includes ["not given this year"]
make(%q(QUANTUM MECHANICS II), '273B', 3, 3).includes ["not given this year"]
make(%q(Evolution Equations in Differential Geometry), '280', 3, 3).includes ["Win"]
make(%q(Low Dimensional Topology), '282A', 3, 3).includes ["Spr"]
make(%q(Homotopy Theory), '282B', 3, 3).includes ["Win"]
make(%q(Fiber Bundles and Cobordism), '282C', 3, 3).includes ["Spr"]
make(%q(Topics in Algebraic and Geometric Topology), '283', 3, 3).includes ["not given this year"]
make(%q(Topics in Topology), '283A', 3, 3).includes ["not given this year"]
make(%q(Topics in Geometric Topology), '284', 3, 3).includes ["Win"]
make(%q(Geometry and Topology in Dimension 3), '284A', 3, 3).includes ["not given this year"]
make(%q(Geometry and Topology in Dimension 3), '284B', 3, 3).includes ["not given this year"]
make(%q(Topics in Differential Geometry), '286', 3, 3).includes ["Win", "Spr"]
make(%q(Introduction to optimal transportation), '287', 3, 3).includes ["not given this year"]
make(%q(Model Theory B (PHIL 350B)), '290B', 1, 3).includes ["Aut"]
make(%q(Set Theory (PHIL 352A)), '292A', 3, 3).includes ["not given this year"]
make(%q(Proof Theory (PHIL 353A)), '293A', 3, 3).includes ["not given this year"]
make(%q(Computation and Algorithms in Mathematics), '295', 3, 3).includes ["not given this year"]
make(%q(Advanced Topics in Convex Optimization), '301', 3, 3).includes ["not given this year"]
make(%q(Top Ten Algorithms of the 20th Century (CME 329)), '310', 3, 3).includes ["Aut"]
make(%q(Graduate Teaching Seminar), '355', 1, 1).includes ["Spr"]
make(%q(Advanced Reading and Research), '360', 1, 10).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Research Seminar Participation), '361', 1, 3).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Seminar in Analysis), '381', 1, 3).includes ["by arrangement"]
make(%q(Qualifying Examination Seminar), '382', 1, 3).includes ["Sum"]
make(%q(Seminar in Geometry), '384', 1, 1).includes ["by arrangement"]
make(%q(Seminar in Topology), '385', 1, 3).includes ["by arrangement"]
make(%q(Seminar in Probability and Stochastic Processes), '388', 1, 3).includes ["by arrangement"]
make(%q(Seminar in Mathematical Biology), '389', 1, 3).includes ["by arrangement"]
make(%q(Research Seminar in Logic and the Foundations of Mathematics (PHIL 391)), '391', 1, 3).includes ["Aut", "Win", "Spr"]
make(%q(Classics in Analysis), '394', 3, 3).includes ["not given this year"]
make(%q(Classics in Geometry and Topology), '395', 3, 3).includes ["not given this year"]
make(%q(Graduate Progress), '396', 1, 1).includes ["not given this year"]
make(%q(TGR Dissertation), '802', 0, 0).includes ["Aut", "Win", "Spr", "Sum"]
            end

            within :ee do
make(%q(How Musical Instruments Work), '10N', 3, 3).includes ["not given this year"]
make(%q(Mathematics of the Information Age), '10SC', 2, 2).includes ["not given this year"]
make(%q(Things about Stuff), '14N', 3, 3).includes ["Aut"]
make(%q(The Art and Science of Engineering Design), '15N', 3, 3).includes ["not given this year"]
make(%q(Engineering the Micro and Nano Worlds: From Chips to Genes), '17N', 3, 3).includes ["Spr"]
make(%q(What is Nanotechnology?), '21N', 3, 3).includes ["Win"]
make(%q(Medical Imaging Systems), '22N', 3, 3).includes ["Win"]
make(%q(Imaging: From the Atom to the Universe), '23N', 3, 3).includes ["not given this year"]
make(%q(Electronics Rocks), '27N', 3, 3).includes ["Win"]
make(%q(Physics of Electrical Engineering (ENGR 40P)), '41', 5, 5).includes ["Win"]
make(%q(Engineering For Good: Save the World and Have Fun Doing It), '46', 3, 3).includes ["Spr"]
make(%q(Press Play: Interactive Device Design), '47', 3, 3).includes ["Sum"]
make(%q(Man versus Nature: Coping with Disasters Using Space Technology (GEOPHYS 60N)), '60N', 4, 4).includes ["not given this year"]
make(%q(Making and Breaking Things), '92A', 1, 1).includes ["Win"]
make(%q(The Electrical Engineering Profession), '100', 1, 1).includes ["Aut"]
make(%q(Circuits and Signals Applications), '100A', 1, 1).includes ["Win"]
make(%q(Circuits I), '101A', 4, 4).includes ["Win"]
make(%q(Circuits II), '101B', 4, 4).includes ["Spr"]
make(%q(Signal Processing and Linear Systems I), '102A', 4, 4).includes ["Win", "Sum"]
make(%q(Signal Processing and Linear Systems II), '102B', 4, 4).includes ["Spr"]
make(%q(Digital Systems I), '108A', 3, 4).includes ["Aut", "Win"]
make(%q(Digital Systems II), '108B', 3, 4).includes ["Aut", "Win"]
make(%q(Digital Systems Design Lab), '109', 4, 4).includes ["Spr"]
make(%q(Fundamentals of Analog Integrated Circuit Design (EE 214A)), '114', 3, 3).includes ["Aut"]
make(%q(Semiconductor Device Physics), '116', 3, 3).includes ["Spr"]
make(%q(Introduction to Mechatronics), '118', 4, 4).includes ["not given this year"]
make(%q(Analog Circuits Laboratory), '122A', 3, 3).includes ["Aut"]
make(%q(Introduction to Biomedical Electronics), '122B', 3, 3).includes ["Spr"]
make(%q(Introduction to Neuroelectrical Engineering), '124', 3, 3).includes ["not given this year"]
make(%q(Analog Communications Design Laboratory (EE 233)), '133', 3, 4).includes ["Win"]
make(%q(Introduction to Photonics), '134', 4, 4).includes ["Spr"]
make(%q(Introduction to Nanophotonics and Nanostructures), '136', 3, 3).includes ["Spr"]
make(%q(Engineering Electromagnetics), '141', 3, 3).includes ["Win"]
make(%q(Sustainable Energy Systems), '151', 3, 3).includes ["not given this year"]
make(%q(Green Electronics), '152', 4, 4).includes ["Aut"]
make(%q(Introduction to Digital Image Processing), '168', 3, 4).includes ["Win"]
make(%q(Introduction to Bioimaging), '169', 3, 3).includes ["not given this year"]
make(%q(Probabilistic Systems Analysis (EE 278A)), '178', 3, 4).includes ["Aut", "Spr"]
make(%q(Analog and Digital Communication Systems), '179', 3, 3).includes ["Spr"]
make(%q(Special Studies or Projects in Electrical Engineering), '190', 1, 15).includes ["Aut", "Win", "Spr"]
make(%q(Special Studies and Reports in Electrical Engineering), '191', 1, 15).includes ["Aut", "Win", "Spr"]
make(%q(Special Studies and Reports in Electrical Engineering), '191A', 1, 1).includes ["Aut", "Win", "Spr"]
make(%q(Special Studies and Reports in Electrical Engineering (WIM)), '191W', 3, 10).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Electrical Engineering in Biology and Medicine), '202', 3, 3).includes ["not given this year"]
make(%q(The Entrepreneurial Engineer), '203', 1, 1).includes ["Win"]
make(%q(Business Management for Electrical Engineers and Computer Scientists), '204', 3, 3).includes ["Spr"]
make(%q(Business Management for Electrical Engineers and Computer Scientists), '204S', 3, 3).includes ["Spr"]
make(%q(Integrated Circuit Fabrication Processes), '212', 3, 3).includes ["Aut"]
make(%q(Fundamentals of Analog Integrated Circuit Design (EE 114)), '214A', 3, 3).includes ["Aut"]
make(%q(Advanced Analog Integrated Circuit Design), '214B', 3, 3).includes ["Win"]
make(%q(Principles and Models of Semiconductor Devices), '216', 3, 3).includes ["Aut", "Win", "Sum"]
make(%q(Applied Quantum Mechanics I), '222', 3, 3).includes ["Aut"]
make(%q(Applied Quantum Mechanics II), '223', 3, 3).includes ["Win"]
make(%q(Bio-chips, Imaging and Nanomedicine (MATSCI 382, SBIO 225)), '225', 3, 3).includes ["Win"]
make(%q(Basic Physics for Solid State Electronics), '228', 3, 3).includes ["not given this year"]
make(%q(Analog Communications Design Laboratory (EE 133)), '233', 3, 4).includes ["Win"]
make(%q(Photonics Laboratory), '234', 3, 3).includes ["Aut"]
make(%q(Modern Optics), '236A', 3, 3).includes ["Aut"]
make(%q(MODERN OPTICS - LABORATORY), '236AL', 1, 1).includes ["Aut"]
make(%q(Guided Waves), '236B', 3, 3).includes ["Win"]
make(%q(Lasers), '236C', 3, 3).includes ["Spr"]
make(%q(Solar Energy Conversion), '237', 3, 3).includes ["Spr"]
make(%q(Electromagnetic Waves), '242', 3, 3).includes ["Spr"]
make(%q(Semiconductor Optoelectronic Devices), '243', 3, 3).includes ["Win"]
make(%q(Introduction to Optical Fiber Communications), '247', 3, 3).includes ["Aut"]
make(%q(Fundamentals of Noise Processes), '248', 3, 3).includes ["Aut"]
make(%q(High-Frequency Circuit Design Laboratory), '251', 3, 3).includes ["Aut"]
make(%q(Antenna Theory), '252', 3, 3).includes ["Aut"]
make(%q(Electrical Systems Practicum (CEE 252E)), '252E', 1, 1).includes ["Win"]
make(%q(Numerical Electromagnetics), '256', 3, 3).includes ["Spr"]
make(%q(Applied Optimization Laboratory (Geophys 258) (GEOPHYS 258)), '257', 3, 4).includes ["not given this year"]
make(%q(The Fourier Transform and Its Applications), '261', 3, 3).includes ["Aut", "Win", "Sum"]
make(%q(Two-Dimensional Imaging), '262', 3, 3).includes ["not given this year"]
make(%q(Introduction to Linear Dynamical Systems (CME 263)), '263', 3, 3).includes ["Aut", "Sum"]
make(%q(Digital Signal Processing), '264', 3, 3).includes ["Aut", "Spr", "Sum"]
make(%q(Digital Signal Processing Laboratory), '265', 3, 4).includes ["not given this year"]
make(%q(Introduction to VLSI Systems), '271', 3, 3).includes ["Aut"]
make(%q(Design Projects in VLSI Systems), '272', 3, 4).includes ["not given this year"]
make(%q(Digital Systems Engineering), '273', 3, 3).includes ["not given this year"]
make(%q(Probabilistic Systems Analysis (EE 178)), '278A', 3, 4).includes ["Aut", "Spr"]
make(%q(Introduction to Statistical Signal Processing), '278B', 3, 3).includes ["Aut", "Win", "Sum"]
make(%q(Introduction to Digital Communication), '279', 3, 3).includes ["Win"]
make(%q(Computer Systems Architecture), '282', 3, 3).includes ["Spr"]
make(%q(Introduction to Computer Networks), '284', 3, 3).includes ["not given this year"]
make(%q(Curricular Practical Training for Electrical Engineers), '290A', 1, 1).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Curricular Practical Training for Electrical Engineers), '290B', 1, 1).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Curricular Practical Training for Electrical Engineers), '290C', 1, 1).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Curricular Practical Training for Electrical Engineers), '290D', 1, 1).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Micro and Nanoscale Biosensing for Molecular Diagnostics), '292B', 3, 3).includes ["Spr"]
make(%q(Chemical Vapor Deposition and Epitaxy for Integrated Circuits and Nanostructures), '292C', 1, 1).includes ["Aut"]
make(%q(Engineering and Climate Change), '292H', 1, 1).includes ["Aut"]
make(%q(Insanely Great Products: How do they get built?), '292I', 1, 1).includes ["Spr"]
make(%q(Power Electronics), '292J', 3, 3).includes ["Spr"]
make(%q(Intelligent Energy Projects), '292K', 3, 3).includes ["not given this year"]
make(%q(Nanomanufacturing), '292L', 3, 3).includes ["Aut"]
make(%q(Parallel Processors Beyond Multi-Core Processing), '292M', 2, 2).includes ["not given this year"]
make(%q(Power Management Integrated Circuits), '292P', 3, 3).includes ["Aut"]
make(%q(SmartGrids and Advanced Power Systems Seminar (CEE 272T)), '292T', 1, 2).includes ["Win", "Spr"]
make(%q(Solar Cells, Fuel Cells, and Batteries: Materials for the Energy Solution (ENERGY 293A, MATSCI 156, MATSCI 256)), '293A', 3, 4).includes ["Aut"]
make(%q(Fundamentals of Energy Processes (ENERGY 293B)), '293B', 3, 3).includes ["Win"]
make(%q(Master's Thesis and Thesis Research), '300', 1, 15).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Autonomous Implantable Systems), '303', 3, 3).includes ["Win"]
make(%q(Neuromorphics: Brains in Silicon (BIOE 313)), '304', 3, 3).includes ["Spr"]
make(%q(Advanced Circuit Techniques), '308', 3, 3).includes ["Spr"]
make(%q(Semiconductor Memory Devices and Technology), '309', 3, 3).includes ["Aut"]
make(%q(Integrated Circuits Technology and Design Seminar), '310', 1, 1).includes ["not given this year"]
make(%q(Advanced Integrated Circuits Technology), '311', 3, 3).includes ["Spr"]
make(%q(Digital MOS Integrated Circuits), '313', 3, 3).includes ["Win"]
make(%q(RF Integrated Circuit Design), '314A', 3, 3).includes ["Spr"]
make(%q(Advanced RF Integrated Circuit Design), '314B', 3, 3).includes ["Aut"]
make(%q(VLSI Signal Conditioning Circuits), '315A', 3, 3).includes ["alternate years", "given next year"]
make(%q(VLSI Data Conversion Circuits), '315B', 3, 3).includes ["Aut", "alternate years", "not given next year"]
make(%q(Advanced VLSI Devices), '316', 3, 3).includes ["Win"]
make(%q(Advanced Nanoelectronic Devices and Technology), '319', 3, 3).includes ["alternate years", "given next year"]
make(%q(Nanoelectronics), '320', 3, 3).includes ["not given this year"]
make(%q(Properties of Semiconductor Materials), '327', 3, 3).includes ["not given this year"]
make(%q(Physics of Advanced Semiconductor Devices), '328', 3, 3).includes ["Spr"]
make(%q(The Electronic Structure of Surfaces and Interfaces (PHOTON 329)), '329', 3, 3).includes ["Aut"]
make(%q(Biophotonics: Light in Medicine and Biology), '331', 3, 3).includes ["Win"]
make(%q(Laser Dynamics), '332', 3, 3).includes ["Win"]
make(%q(Micro and Nano Optical Device Design), '334', 3, 3).includes ["not given this year"]
make(%q(Nanophotonics (MATSCI 346)), '336', 3, 3).includes ["Aut"]
make(%q(Optical Micro- and Nano-Cavities), '340', 3, 3).includes ["not given this year"]
make(%q(Optical Fiber Communication Laboratory), '345', 3, 3).includes ["alternate years", "given next year"]
make(%q(Introduction to Nonlinear Optics), '346', 3, 3).includes ["alternate years", "not given next year"]
make(%q(Advanced Optical Fiber Communications), '348', 3, 3).includes ["Win"]
make(%q(Imaging Radar and Applications (GEOPHYS 265)), '355', 3, 3).includes ["Win"]
make(%q(Wireless Communications), '359', 3, 4).includes ["Aut"]
make(%q(Multiuser Wireless Systems and Networks), '360', 3, 3).includes ["Win"]
make(%q(Principles of Cooperation in Wireless Networks), '361', 3, 3).includes ["not given this year"]
make(%q(Convex Optimization I (CME 364A, CS 334A)), '364A', 3, 3).includes ["Win", "Sum"]
make(%q(Convex Optimization II (CME 364B)), '364B', 3, 3).includes ["Spr"]
make(%q(STOCHASTIC CONTROL), '365', 3, 3).includes ["Spr"]
make(%q(Digital Image Processing (CS 232)), '368', 3, 3).includes ["Aut", "Win", "Spr"]
make(%q(Medical Imaging Systems I), '369A', 3, 3).includes ["not given this year"]
make(%q(Medical Imaging Systems II), '369B', 3, 3).includes ["Spr"]
make(%q(Medical Image Reconstruction), '369C', 3, 3).includes ["Aut"]
make(%q(Advanced VLSI Circuit Design), '371', 3, 3).includes ["alternate years", "given next year"]
make(%q(Adaptive Signal Processing), '373A', 3, 3).includes ["Win"]
make(%q(Adaptive Neural Networks), '373B', 3, 3).includes ["not given this year"]
make(%q(Information Theory (STATS 376A)), '376A', 3, 3).includes ["Win"]
make(%q(Network Information Theory), '376B', 3, 3).includes ["not given this year"]
make(%q(Universal Schemes in Information Theory), '376C', 3, 3).includes ["Spr"]
make(%q(Statistical Signal Processing), '378A', 3, 3).includes ["not given this year"]
make(%q(Inference, Estimation, and Information Processing), '378B', 3, 3).includes ["not given this year"]
make(%q(Digital Communication), '379', 3, 3).includes ["not given this year"]
make(%q(Colloquium on Computer Systems), '380', 1, 1).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Interconnection Networks), '382C', 3, 3).includes ["not given this year"]
make(%q(Advanced Multi-Core Systems (CS 316)), '382E', 3, 3).includes ["Aut"]
make(%q(Internet Routing Protocols and Standards), '384A', 3, 3).includes ["not given this year"]
make(%q(Wireless Local and Wide Area Networks), '384C', 3, 3).includes ["not given this year"]
make(%q(Network Science), '384M', 3, 3).includes ["not given this year"]
make(%q(Performance Engineering of Computer Systems & Networks), '384S', 3, 3).includes ["Spr"]
make(%q(Packet Switch Architectures), '384X', 3, 3).includes ["alternate years", "given next year"]
make(%q(Robust and Testable Systems Seminar), '385A', 1, 4).includes ["Aut", "Win", "Spr"]
make(%q(Robust System Design), '386', 3, 3).includes ["alternate years", "given next year"]
make(%q(Algebraic Error Control Codes), '387', 3, 3).includes ["not given this year"]
make(%q(Special Studies or Projects in Electrical Engineering), '390', 1, 15).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Special Studies and Reports in Electrical Engineering), '391', 1, 15).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(VLSI Signal Processing), '392E', 3, 3).includes ["not given this year"]
make(%q(Logic Synthesis of VLSI Circuits), '392F', 3, 3).includes ["not given this year"]
make(%q(Seminar on Trends in Computing and Communications), '392I', 1, 1).includes ["Spr"]
make(%q(Modern Cellular Communication Systems), '392L', 3, 3).includes ["Spr"]
make(%q(INTELLIGENT ENERGY SYSTEMS), '392N', 1, 1).includes ["Spr"]
make(%q(Nanoscale Device Physics), '392P', 3, 3).includes ["not given this year"]
make(%q(Parallel Processors Beyond Multicore Processing), '392Q', 3, 3).includes ["Win"]
make(%q(Seminar in Chip Test and Debug), '392T', 1, 1).includes ["Win"]
make(%q(Electrical Engineering Instruction: Practice Teaching), '395', 1, 15).includes ["Aut", "Win", "Spr"]
make(%q(Engineering Education and Online Learning (EDUC 391X)), '396', 3, 3).includes ["Spr"]
make(%q(Image and Video Compression), '398A', 3, 3).includes ["not given this year"]
make(%q(Thesis and Thesis Research), '400', 1, 15).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(Topics in International Technology Management), '402A', 1, 1).includes ["Aut"]
make(%q(Topics in International Advanced Technology Research), '402S', 1, 1).includes ["not given this year"]
make(%q(Entrepreneurship in Asian High-Tech Industries), '402T', 1, 1).includes ["Spr"]
make(%q(Integrated Circuit Fabrication Laboratory), '410', 3, 4).includes ["Win"]
make(%q(Advanced Nanofabrication Laboratory), '412', 3, 3).includes ["Spr"]
make(%q(RF Transceiver Design Laboratory), '414', 3, 3).includes ["Win"]
make(%q(Semidefinite Optimization and Algebraic Techniques), '464', 3, 3).includes ["not given this year"]
make(%q(RF Pulse Design for Magnetic Resonance Imaging), '469B', 3, 3).includes ["not given this year"]
make(%q(TGR Project), '801', 0, 0).includes ["Aut", "Win", "Spr", "Sum"]
make(%q(TGR Dissertation), '802', 0, 0).includes ["Aut", "Win", "Spr", "Sum"]
            end
        end
    end
end
